Pages/Shop/Cart.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using FitComrade.Entities;
using FitComrade.Models;
using FitComrade.Helpers;

namespace FitComrade.Pages.Shop
{
    public class CartModel : PageModel
    {
        private readonly FitComrade.Data.FitComradeContext _context;

        public CartModel(FitComrade.Data.FitComradeContext context)
        {
            _context = context;
        }

        public List<Item> cart { get; set; }
        public decimal Total { get; set; }

        public void OnGet()
        {
            cart = SessionHelper.GetObjectFromJson<List<Item>>(HttpContext.Session, "cart");
            decimal itemTotal;
            Total = 0;
            foreach (var item in cart)
            {
                itemTotal = cart.Sum(i => i.Products.SellPrice * i.Quantity);
                Total = +itemTotal;
            }
        }

        public IActionResult OnGetBuyNow(int id)
        {
            var productModel = new ProductModel(_context);
            cart = SessionHelper.GetObjectFromJson<List<Item>>(HttpContext.Session, "cart");
            if (cart == null)
            {
                cart = new List<Item>();
                cart.Add(new Item
                {
                    Products = productModel.Find(id),
                    Quantity = 1
                });
                SessionHelper.SetObjectAsJson(HttpContext.Session, "cart", cart);
                SessionHelper.myUser.ShoppingCart = cart;
            }
            else
            {
                int index = Exists(cart, id);
                if (index == -1)
                {
                    cart.Add(new Item
                    {
                        Products = productModel.Find(id),
                        Quantity = 1
                    });
                }
                else
                {
                    cart[index].Quantity++;
                }
                SessionHelper.SetObjectAsJson(HttpContext.Session, "cart", cart);
                SessionHelper.myUser.ShoppingCart = cart;
            }
            return RedirectToPage("Cart");
        }

        public IActionResult OnGetDelete(int id)
        {
            //cart = SessionHelper.GetObjectFromJson<List<Item>>(HttpContext.Session, "cart");
            cart = SessionHelper.myUser.ShoppingCart;
            int index = Exists(cart, id);
            cart.RemoveAt(index);
            SessionHelper.SetObjectAsJson(HttpContext.Session, "cart", cart);
            
            return RedirectToPage("Cart");
        }

        public IActionResult OnPostUpdate(int[] quantities)
        {
            //cart = SessionHelper.GetObjectFromJson<List<Item>>(HttpContext.Session, "cart");
            cart = SessionHelper.myUser.ShoppingCart;
            for (var i = 0; i < cart.Count; i++)
            {
                cart[i].Quantity = quantities[i];
            }
            SessionHelper.SetObjectAsJson(HttpContext.Session, "cart", cart);
            
            return RedirectToPage("Cart");
        }

        private int Exists(List<Item> cart, int id)
        {
            for (var i = 0; i < cart.Count; i++)
            {
                if (cart[i].Products.ID == id)
                {
                    return i;
                }
            }
            return -1;
        }

    }
}

Pages/Shop/Checkout.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using FitComrade.Entities;
using FitComrade.Models;
using FitComrade.Helpers;
using Microsoft.EntityFrameworkCore;

namespace FitComrade.Pages.Shop
{
    public class CheckoutModel : PageModel
    {
        private readonly FitComrade.Data.FitComradeContext _context;

        public CheckoutModel(FitComrade.Data.FitComradeContext context)
        {
            _context = context;
        }

        public List<Item> cart { get; set; }
        public decimal Total { get; set; }
        private decimal discount = 1;
        [BindProperty]
        public Order Order { get; set; }
        
        

        public void OnGet()
        {
            cart = SessionHelper.myUser.ShoppingCart;
            decimal itemTotal;
            Total = 0;
            if(cart != null)
            {
                foreach (var item in cart.Where(item => item != null))
                {
                    itemTotal = cart.Sum(i => i.Products.SellPrice * i.Quantity);
                    Total = +itemTotal;
                }
            }
            


        }
        public async Task<IActionResult> OnPostAsync() // Betalen
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }
            cart = SessionHelper.myUser.ShoppingCart;
            decimal itemTotal;
            Total = 0;
            if (cart != null)
            {
                foreach (var item in cart.Where(item => item != null))
                {
                    itemTotal = cart.Sum(i => i.Products.SellPrice * i.Quantity);
                    Total = +itemTotal;
                }
            }

            Order.Paid = true;  //Fake Payment
            Order.TotalPrice = Total;
            Order.OrderDate = DateTime.Now;
            Order.Username = SessionHelper.myUser.UserName; //Als gebruiker is ingelogd

            
            
            _context.Orders.Add(Order);
            _context.SaveChanges();
            if (Order.Paid == true)
            {
                
                int id = Order.ID;
                if (cart != null)
                {
                    foreach (var item in cart.Where(item => item != null))
                    {
                        _context.OrderDetails.Add(new OrderDetail
                        {
                            OrderID = id,
                            ProductID = item.Products.ID,
                            OrderNumber = _context.Orders.Count(),
                            Price = item.Products.SellPrice,
                            Quantity = item.Quantity,
                            Discount = discount,
                            Total = item.Products.SellPrice * item.Quantity * discount,
                            BillDate = DateTime.Now,
                        });
                        item.Products.Store = item.Products.Store - item.Quantity;
                        _context.Attach(item.Products).State = EntityState.Modified;

                        
                    }
                }

            }

            
            await _context.SaveChangesAsync();
            return RedirectToPage("/Index");
        }
    }
}

Pages/Shop/Index.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using FitComrade.Entities;
using FitComrade.Models;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace FitComrade.Pages.Shop
{
    public class IndexModel : PageModel
    {
        public List<Products> Products;
        private readonly FitComrade.Data.FitComradeContext _context;
        [BindProperty(SupportsGet = true)]
        public string SearchString { get; set; }
        public SelectList Category { get; set; }
        public IndexModel(FitComrade.Data.FitComradeContext context)
        {
            _context = context;
        }
        public void OnGet()
        {
            ProductModel productModel = new ProductModel(_context);
            Products = productModel.FindAll();

            
            if (!string.IsNullOrEmpty(SearchString))
            {
                Products = productModel.FindProductName(SearchString);
            }
            
        }
        
    }
}

Pages/Shop/Cart.cshtml
@page
@model FitComrade.Pages.Shop.CartModel
@{
}
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Cart</title>
</head>
<body>

    <h3>Winkelmand</h3>
    <form method="post" asp-page="cart" asp-page-handler="update">
        <table class="table">
            <tr>
                <th></th>
                <th>ArtikelNr.</th>
                <th>Product</th>
                <th>Photo</th>
                <th>Prijs</th>
                <th>Aantal <input type="submit" value="Update" /></th>
                <th>Totaalprijs</th>
            </tr>
            @foreach (var item in Model.cart)
            {
                <tr align="center">
                    <td align="center">
                        <a asp-page="cart" asp-page-handler="delete" asp-route-id="@item.Products.ID">Verwijder</a>
                    </td>
                    <td>@item.Products.ID</td>
                    <td>@item.Products.ProductName</td>
                    <td><img src="~/images/FitComrade logo.png" width="100" height="100" /></td>
                    <td>$@item.Products.SellPrice</td>
                    <td><input type="number" name="quantities" value="@item.Quantity" min="1" style="width: 50px;" /></td>
                    <td>
                        €@(item.Products.SellPrice * item.Quantity)
                    </td>
                </tr>
            }
            <tr>
                <td colspan="6" align="right">Totaal</td>
                <td align="center">€@Model.Total</td>
                <td>
                    <a asp-page="Checkout">Betaal</a>
                </td>
            </tr>
        </table>
    </form>
    <a asp-page="index">Doorgaan met winkelen</a>
    
</body>
</html>

Pages/Shop/Checkout.cshtml
@page
@model FitComrade.Pages.Shop.CheckoutModel
@{
}
<head>
    <link rel="stylesheet" href="~/css/CheckoutStyle.css" />
</head>
<div class="row">
    <div class="col-75">
        <div class="container">
            <form method="post">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <div class="row">
                    <div class="col-50">
                        <h3>Gegevens</h3>
                        <div class="form-group">
                            <label asp-for="Order.FirstName" class="control-label"></label>
                            <input asp-for="Order.FirstName" class="form-control" />
                            <span asp-validation-for="Order.FirstName" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="Order.LastName" class="control-label"></label>
                            <input asp-for="Order.LastName" class="form-control" />
                            <span asp-validation-for="Order.LastName" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="Order.Email" class="control-label"></label>
                            <input asp-for="Order.Email" class="form-control" />
                            <span asp-validation-for="Order.Email" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="Order.PostalCode" class="control-label"></label>
                            <input asp-for="Order.PostalCode" class="form-control" />
                            <span asp-validation-for="Order.PostalCode" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="Order.Address" class="control-label"></label>
                            <input asp-for="Order.Address" class="form-control" />
                            <span asp-validation-for="Order.Address" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="Order.City" class="control-label"></label>
                            <input asp-for="Order.City" class="form-control" />
                            <span asp-validation-for="Order.City" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="Order.Country" class="control-label"></label>
                            <input asp-for="Order.Country" class="form-control" />
                            <span asp-validation-for="Order.Country" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="Order.Phone" class="control-label"></label>
                            <input asp-for="Order.Phone" class="form-control" />
                            <span asp-validation-for="Order.Phone" class="text-danger"></span>
                        </div>


                    </div>

                    <div class="col-50">
                        <h3>Betaling</h3>                        
                        <div class="form-group">
                            <label asp-for="Order.Payment" class="control-label"></label>
                            <input asp-for="Order.Payment" class="form-control" />
                            <span asp-validation-for="Order.Payment" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="Order.Bank" class="control-label"></label>
                            <input asp-for="Order.Bank" class="form-control" />
                            <span asp-validation-for="Order.Bank" class="text-danger"></span>
                        </div>
                        
                    </div>

                </div>
                <label>
                    <input type="checkbox" checked="checked" name="sameadr"> Factuur naar hetzelfde adress als verzending
                </label>
                <input type="submit" value="Verder naar betaling" class="btn">
            </form>
        </div>
    </div>

    @{
        decimal TotalPrice = 0;
        <div class="col-25">
            <div class="container">
                <h4>
                    Winkelmand
                    <span class="price" style="color:black">
                        <i class="fa fa-shopping-cart"></i>

                    </span>
                </h4>
                @foreach (var item in Model.cart)
                {
                    var price = item.Products.SellPrice * item.Quantity;
                    <p><a>@item.Products.ProductName</a> <span class="price">€@price</span></p>
                    TotalPrice = TotalPrice + price;
                }
                <hr>
                <p>Totaal <span class="price" style="color:black"><b>€@TotalPrice</b></span></p>
            </div>
        </div>
    }
</div>
@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Pages/Shop/Index.cshtml
@page
@model FitComrade.Pages.Shop.IndexModel
@{
}
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Shop</title>
</head>
<body>

    <h3>Producten</h3>
    <form>
        <p>
            Zoek Product: <input type="text" asp-for="SearchString" />
            <input type="submit" value="Filter" />
        </p>
    </form>
    
    <table class="table">
        <tr>
            <th>Nr.</th>
            <th>Product</th>
            <th>Foto</th>
            <th>Category</th>
            <th>Prijs</th>
            <th>Voorraad</th>
            <th></th>

        </tr>
        @foreach (var product in Model.Products)
        {
            <tr>
                <td>@product.ID</td>
                <td>@product.ProductName</td>
                <td><img src="~/images/FitComrade logo.png" width="100" height="100" /></td>
                <td>@product.Category</td>
                <td>€@product.SellPrice</td>
                <td>@product.Store</td>
                <td>
                    <a asp-page="cart" asp-page-handler="buynow" asp-route-id="@product.ID">Bestel</a>
                </td>
            </tr>
        }
    </table>

</body>
</html>